Variables added

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -51,44 +51,44 @@ jobs:
               files:
                 - source: .
                   destination: $APPSPEC_DESTINATION" > appspec.yml      
-        # - run:
-        #     name: Run Build
-        #     command: npm run build
-        # - run:
-        #     name: Compress Artifacts
-        #     command: zip -qr $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO_ID.zip ./dist appspec.yml
-        # - aws-s3/copy:
-        #     from: $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO_ID.zip 
-        #     to: $AWS_BUCKET_LOCATION_V2 
-        # - run:    
-        #     name: Iniitate Code-Deploy
-        #     command: |
-        #         echo "pushing to DEV..." 
-        #         ID=$(aws deploy create-deployment \
-        #             --application-name $APP_NAME_V2 \
-        #             --deployment-config-name CodeDeployDefault.AllAtOnce \
-        #             --deployment-group-name $CODE_DEPLOYMENT_GROUP_DEV \
-        #             --s3-location bucket=symmetric-pools-ui-bucket,bundleType=zip,key=V2/$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO_ID.zip \
-        #             --description "$GIT_COMMIT_MSG" \
-        #             --output text \
-        #             --query 'deploymentId')
-        #         echo $ID      
-        #         STATUS=$(aws deploy get-deployment --deployment-id $ID --output text --query 'deploymentInfo.status')
-        #         echo "STATUS: $STATUS..."
-        #         while [[ $STATUS == "Created" || $STATUS == "InProgress" || $STATUS == "Pending" || $STATUS == "Queued" || $STATUS == "Ready" ]]; do
-        #                 echo "Status: $STATUS..."
-        #                 STATUS=$(aws deploy get-deployment --deployment-id $ID --output text --query 'deploymentInfo.status')
-        #                 sleep 5
-        #               done
-        #               if [[ $STATUS == "Succeeded" ]]; then
-        #                 EXITCODE=0
-        #                 echo "Deployment finished."
-        #               else
-        #                 EXITCODE=1
-        #                 echo "Deployment failed!"
-        #               fi
-        #               aws deploy get-deployment --deployment-id $ID
-        #               exit $EXITCODE
+        - run:
+            name: Run Build
+            command: npm run build
+        - run:
+            name: Compress Artifacts
+            command: zip -qr $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO_ID.zip ./dist appspec.yml
+        - aws-s3/copy:
+            from: $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO_ID.zip 
+            to: $AWS_BUCKET_LOCATION_V2 
+        - run:    
+            name: Iniitate Code-Deploy
+            command: |
+                echo "pushing to DEV..." 
+                ID=$(aws deploy create-deployment \
+                    --application-name $APP_NAME_V2 \
+                    --deployment-config-name CodeDeployDefault.AllAtOnce \
+                    --deployment-group-name $CODE_DEPLOYMENT_GROUP_DEV \
+                    --s3-location bucket=symmetric-pools-ui-bucket,bundleType=zip,key=V2/$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO_ID.zip \
+                    --description "$GIT_COMMIT_MSG" \
+                    --output text \
+                    --query 'deploymentId')
+                echo $ID      
+                STATUS=$(aws deploy get-deployment --deployment-id $ID --output text --query 'deploymentInfo.status')
+                echo "STATUS: $STATUS..."
+                while [[ $STATUS == "Created" || $STATUS == "InProgress" || $STATUS == "Pending" || $STATUS == "Queued" || $STATUS == "Ready" ]]; do
+                        echo "Status: $STATUS..."
+                        STATUS=$(aws deploy get-deployment --deployment-id $ID --output text --query 'deploymentInfo.status')
+                        sleep 5
+                      done
+                      if [[ $STATUS == "Succeeded" ]]; then
+                        EXITCODE=0
+                        echo "Deployment finished."
+                      else
+                        EXITCODE=1
+                        echo "Deployment failed!"
+                      fi
+                      aws deploy get-deployment --deployment-id $ID
+                      exit $EXITCODE
               
 
 workflows:
